"""Shared fixtures for the test suite.

`tests/` had no conftest before this. test_export_api.py does
`from tests.test_generate_report_api import ...` and works only because pytest
inserts the rootdir on sys.path when it finds no package marker - a conftest here
makes that explicit rather than incidental.

The corpus fixtures are session-scoped: discovery walks tests/data/ once per run
rather than once per parametrised case.
"""

import os

import pytest
from fastapi.testclient import TestClient

import app.api as api
from app.data import session_store
from tests import loading_checks


@pytest.fixture(autouse=True)
def isolated_telemetry_db(tmp_path, monkeypatch):
    """Point telemetry at a throwaway database for every test in the suite.

    Autouse and unconditional on purpose. Once api.py is instrumented, any test
    that touches an endpoint writes telemetry as a side effect, and without this
    the suite would accumulate junk rows in the developer's real usage.db - and
    then GET /api/stats would report numbers nobody generated by using the app.

    telemetry reads TELEMETRY_DB per call rather than at import, which is what
    makes monkeypatch.setenv effective here. Tests that want a specific database
    (tests/test_telemetry.py) override this with their own setenv, which runs
    after this fixture and wins.
    """
    monkeypatch.setenv("TELEMETRY_DB", str(tmp_path / "usage.db"))
    # Also neutralise the plaintext-names flag. app/data/AI_Engine.py calls
    # load_dotenv() at import, so a developer with TELEMETRY_STORE_NAMES=1 in their
    # .env has it in os.environ for the whole run - and the privacy assertions
    # would then pass or fail depending on whose machine the suite is on. Deleting
    # it here sticks, because nothing calls load_dotenv() again after import.
    monkeypatch.delenv("TELEMETRY_STORE_NAMES", raising=False)


@pytest.fixture(autouse=True)
def isolated_session_store(tmp_path, monkeypatch):
    """Point the session snapshot store at a throwaway directory, and turn it off.

    Same "whose machine is the suite on" reasoning as isolated_telemetry_db. A
    developer with SAVE_REPORT_HISTORY=true in their .env has it in os.environ for
    the whole run (AI_Engine calls load_dotenv() at import), so without deleting it
    here every upload test would write real session_data/<id>/ directories onto
    their disk - holding copies of the corpus workbooks - and the "history is off by
    default" assertions would pass or fail depending on the machine.

    SESSION_ROOT is patched as well as the flag, so a test that opts back in with
    monkeypatch.setenv still writes into tmp_path rather than the working tree.
    """
    monkeypatch.delenv("SAVE_REPORT_HISTORY", raising=False)
    monkeypatch.setattr(session_store, "SESSION_ROOT", tmp_path / "session_data")
    # report_builder writes its per-report trace into a session_data/ path of its
    # own, which SESSION_ROOT above does not govern - so on a machine with
    # SAVE_DEBUG_FILES=true in .env the suite was dropping report_debug_*.txt into
    # the working tree. It reads the flag per call, so deleting it here takes
    # effect. (AI_Engine captures the same variable at import and is unaffected;
    # nothing in the suite reaches its write path.)
    monkeypatch.delenv("SAVE_DEBUG_FILES", raising=False)


@pytest.fixture(scope="session")
def data_dir():
    return loading_checks.DATA_ROOT


@pytest.fixture
def client():
    return TestClient(api.app)


@pytest.fixture(scope="session")
def baseline():
    return loading_checks.load_baseline()


@pytest.fixture(scope="session")
def inbox_baseline():
    return loading_checks.load_baseline(loading_checks.INBOX_BASELINE_PATH)


def require_corpus(cases, folder):
    """Skip rather than fail when a corpus folder is missing or empty.

    A partial checkout should report zero cases, not a wall of red. The demo path
    is the other way round: scripts/run_test_plan.py --strict turns a missing
    *required* corpus into an error, so an empty folder can't pass for a green run
    on the day. tests/data/inbox/ is exempt from that - being empty is its normal
    state on every machine but the one that filled it.
    """
    if not cases:
        pytest.skip(
            f"no test cases discovered in {folder} - "
            f"corpus missing or empty (this is expected on a partial checkout)"
        )


def case_ids(cases):
    return [c["id"] for c in cases]


def _discover(fn, root):
    return fn(root) if os.path.isdir(root) else []


EXTENSION_CASES = _discover(
    loading_checks.discover_extension_cases, loading_checks.EXTENSIONS_ROOT
)
WORKBOOK_CASES = _discover(
    loading_checks.discover_workbook_cases, loading_checks.WORKBOOKS_ROOT
)
INBOX_CASES = _discover(
    loading_checks.discover_inbox_cases, loading_checks.INBOX_ROOT
)
