"""Fixtures shared by the file-loading suites.

Nothing here is autouse, so the four pre-existing test modules are unaffected --
they keep their own `client` and their own session cleanup. Where a name here
collides with one defined inside a test module (`client` does), pytest resolves
to the nearest definition, so the module's version still wins.

The manifest and fixture paths are not defined here: tests/loading_checks.py
owns them, because scripts/run_test_plan.py needs the same values and cannot
reach pytest fixtures.
"""

import pytest

from tests import loading_checks


@pytest.fixture(autouse=True, scope="session")
def _isolate_telemetry_db(tmp_path_factory):
    """Point every test's telemetry writes at a throwaway database.

    Autouse and session-scoped because the leak this prevents is silent and easy
    to reintroduce. Any test that drives an instrumented endpoint -- /api/inspect,
    /api/analyze-full, /api/generate-report -- writes a telemetry row, and without
    this it lands in the developer's real usage.db at the repo root. The result is
    a home page showing counts invented by the test suite, which is both wrong and
    confusing to debug.

    Individual modules still set TELEMETRY_DB to their own tmp_path for
    per-test isolation; this is the floor that catches everything else.
    """
    import os

    path = tmp_path_factory.mktemp("telemetry") / "usage.db"
    previous = os.environ.get("TELEMETRY_DB")
    os.environ["TELEMETRY_DB"] = str(path)
    yield
    if previous is None:
        os.environ.pop("TELEMETRY_DB", None)
    else:
        os.environ["TELEMETRY_DB"] = previous


@pytest.fixture(scope="session")
def fixture_dir():
    """tests/fixtures -- the manifest and the non-Excel fixtures live here."""
    return loading_checks.FIXTURE_DIR


@pytest.fixture(scope="session")
def excel_dir():
    """tests/fixtures/excel -- generated by scripts/make_test_fixtures.py."""
    return loading_checks.EXCEL_DIR


@pytest.fixture(scope="session")
def manifest():
    """The whole parsed manifest, including its schema_version and comments."""
    return loading_checks.load_manifest()


@pytest.fixture(scope="session")
def cases():
    """The validated case list.

    Session-scoped because the manifest is read-only; tests that need to
    parametrize over cases call loading_checks.load_cases() at import time
    instead, since parametrization happens before fixtures exist.
    """
    return loading_checks.load_cases()


@pytest.fixture
def client():
    """TestClient over the real app, for API-level cases.

    Imported lazily: app.api pulls in pandas, the AI engine and dotenv at import
    time, and unit-level tests that only touch DataLoader should not pay for
    that or require the environment it expects.
    """
    from fastapi.testclient import TestClient

    import app.api as api

    return TestClient(api.app)
